// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwDCCe-sAL9DdWqkyCjOq92CsJhQOtvvw',
    appId: '1:508921195092:web:82d2c945662d3f0d3f9bc1',
    messagingSenderId: '508921195092',
    projectId: 'featureflag-80a08',
    authDomain: 'featureflag-80a08.firebaseapp.com',
    storageBucket: 'featureflag-80a08.firebasestorage.app',
    measurementId: 'G-KJCW8SMKD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNwKzfy3uumSPe6Kit_4SpjGJbf7bwd3Y',
    appId: '1:508921195092:android:f951a16566a02a3a3f9bc1',
    messagingSenderId: '508921195092',
    projectId: 'featureflag-80a08',
    storageBucket: 'featureflag-80a08.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA57V55UFfHSs5G-1kYImoFzvHFH6qMN5w',
    appId: '1:508921195092:ios:98fa53bfc12433003f9bc1',
    messagingSenderId: '508921195092',
    projectId: 'featureflag-80a08',
    storageBucket: 'featureflag-80a08.firebasestorage.app',
    iosBundleId: 'com.example.loandsFlutter',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA57V55UFfHSs5G-1kYImoFzvHFH6qMN5w',
    appId: '1:508921195092:ios:98fa53bfc12433003f9bc1',
    messagingSenderId: '508921195092',
    projectId: 'featureflag-80a08',
    storageBucket: 'featureflag-80a08.firebasestorage.app',
    iosBundleId: 'com.example.loandsFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwDCCe-sAL9DdWqkyCjOq92CsJhQOtvvw',
    appId: '1:508921195092:web:b4ed51c025d7432f3f9bc1',
    messagingSenderId: '508921195092',
    projectId: 'featureflag-80a08',
    authDomain: 'featureflag-80a08.firebaseapp.com',
    storageBucket: 'featureflag-80a08.firebasestorage.app',
    measurementId: 'G-JEQKH31WNH',
  );
}
